### PR TITLE
 sql/(plan,expression,parse,analyzer): trace node execution 

### LINKED ISSUE #137: Save performance metrics
It would be good to have saved performance metrics that we can use to understand the changes. As mentioned in #36 these metrics can be saved in `Session` or in `Context`.

Some of the data we can save is:

* Time spent executing nodes
* Memory consumption before and after node execution
* Cache hit/miss
* Child nodes to pinpoint slower paths

The proposal is adding a `Performance` interface to base session or context that can be used to save this data. It's done as an interface so we can have several implementations, some can get more info than others or disable collecting data in case it's too expensive.

```go
type Performance interface {
	// Called once per query to reset the counters
	Reset()

	// Marks the start of one node execution, returns an id as there can be several
	// nodes running at the same time
	Start(nodeName, arguments string) (id int)

	// Marks the start of one node execution
	End(id int)

	// This can be used to save other values like cache hit and miss rates
	ExtraData(id int, name string, value int)

	// Gets the collected data in some structured format like json
	GetData() string
}
```

Then all the nodes have to be instrumented to save this data:

```go
func (ib *IsBinary) Eval(
	ctx *sql.Context,
	row sql.Row,
) (interface{}, error) {
	// Start collecting data
	perID := ctx.Performance.Start("IsBinary", ib.String())
	defer ctx.Performance.End(perID)

	v, err := ib.Child.Eval(ctx, row)

	[...]

	blob, err := sql.Blob.Convert(v)
	if err != nil {
		return nil, err
	}

	// Add extra information that may be useful
	ctx.Performance.ExtraData(perID, "blob size", blob.Size())

	return isBinary(blob.([]byte)), nil
}
```

Extra tooling should be created to read and analyze this data. It would also be interesting to automate running tests with old and new code (for example `master` and PR) and comparing the data to find regressions.

Thoughts? @ajnavarro, @erizocosmico, @mcarmonaa

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #137

Depends on #139 and #138 

This commit adds tracing of spans of execution in all nodes and expressions.

Since expressions and functions evaluation is immediate, spans are finished inside the `Eval` function with a defer.
In the case of plan nodes it's a bit more complex, as they just return an iterator that will be lazily evaluated. Measuring the span as just the time it takes to return the iterator would be wrong, so what it does is wrap all iterators with a `spanIter`, which iterates over an internal iterator and finishes the span when it's needed (there is an error, io.EOF is returned or `Close` is called) pushing some metrics like the number of processed rows or the error without needing the user to provide them.

### CODE REVIEW

File: sql/expression/function/isbinary.go [hunk 1]
```diff
@@ -23,6 +27,21 @@ func (ib *IsBinary) Eval(
 	ctx *sql.Context,
 	row sql.Row,
 ) (interface{}, error) {
+	var blobSize int
+	span, ctx := ctx.Span("function.IsBinary")
+	defer func() {
+		span.FinishWithOptions(opentracing.FinishOptions{
```
Comment (smola) [inline sql/expression/function/isbinary.go]: Soooo verbose :sob:

Comment (erizocosmico) [reply sql/expression/function/isbinary.go]: I know, the API is a bit eugh 😞
