### PR TITLE
sql: implement dummy ROLLBACK

### LINKED ISSUE #563: [SQLAlchemy] ROLLBACK support or workaround
Following discussion from https://github.com/src-d/go-mysql-server/issues/319#issuecomment-441996211

SQLAlchemy sends `ROLLBACK` quite often:
   * [engine/default.py#initialize](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L285)
   * on recovery from any failure
   
This could possibly be worked around though [connection configuration options](https://github.com/zzzeek/sqlalchemy/blob/c99345ee9994c3ea2a5e6536cc3365f18d017cc1/doc/build/faq/connections.rst#why-does-sqlalchemy-issue-so-many-rollbacks), but a workaround is unknown.

Here is a [python snippet](https://gist.github.com/bzz/94c43cb22fa2bf69c09ccb4e47cfe781#python-code) to reproduce this.

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #563

### CODE REVIEW

File: sql/plan/transaction.go [hunk 1]
```diff
@@ -0,0 +1,35 @@
+package plan
+
+import "gopkg.in/src-d/go-mysql-server.v0/sql"
+
+// Rollback undoes the changes perfromed in a transaction.
```
Comment (jfontan) [inline sql/plan/transaction.go]:
```suggestion
// Rollback undoes the changes performed in a transaction.
```

**Comment by erizocosmico** [comment]
@kuba-- yup, just for it not to fail. Some clients to a lot of `ROLLBACK`s, such as SQLAlchemy
