### PR TITLE
sql/analyzer: fix use of declared aliases in the same projection

### LINKED ISSUE #590: alias used on a expression in the same projection should fail always
the following query:
```
select 
    language(blob_content, file_path) as lang, 
    substring(lang,1,1) as result
from refs 
NATURAL JOIN commits 
NATURAL JOIN commit_files 
NATURAL JOIN files 
where lang != '' limit 100;
```
Is returning results, but it should fail with the following error:
`ERROR 1105 (HY000): unknown error: column "lang" does not exist in scope, but there is an alias defined in this projection with that name. Aliases cannot be used in the same projection they're defined in`

### PR DESCRIPTION
**Pull request by mcarmonaa**
Fixes #590 

Since this is just a SQL syntax issue finally I've just added a new rule to check the aliases usage at the beginning of the analysis phase that runs once before the default rules. This way it doesn't interfere with the transformations made by the rest of the rules.

### CODE REVIEW

File: sql/analyzer/rules.go [hunk 1]
```diff
@@ -27,6 +27,7 @@ var DefaultRules = []Rule{
 var OnceBeforeDefault = []Rule{
 	{"resolve_subqueries", resolveSubqueries},
 	{"resolve_tables", resolveTables},
+	{"check_aliases", checkAliases},
```
Comment (erizocosmico) [inline sql/analyzer/rules.go]: this should be a validation rule

Comment (mcarmonaa) [reply sql/analyzer/rules.go]: validation rules are executed after regular rules, this must executed with the parsed plan before transformations

Comment (erizocosmico) [reply sql/analyzer/rules.go]: But it's a validation rule. Why can't it be run in validation phase?

Comment (mcarmonaa) [reply sql/analyzer/rules.go]: Since validation phase runs after the default rules, the plan to be validated could be modified enough to not keep this alias case.

An alias defined and used in the same projection in the original query, it couldn't be there in the plan after the transformations (reorder/remove/pushdown/joins...) (that's the case of the issue).

To be sure that a query which is making this is not allowed, the check must be done on the parsed plan or on a plan near to it.
