### PR TITLE
sql/(analyzer,parse,expression): implement case expression

### LINKED ISSUE #575: CASE statement
We use `CASE WHEN x THEN y` statements inside gitbase-spark-connector, but it's not actually supported inside gitbase, so some queries that use it may fail.

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #575

### CODE REVIEW

File: sql/analyzer/validation_rules.go [hunk 1]
```diff
@@ -46,6 +53,7 @@ var DefaultValidationRules = []Rule{
 	{validateSchemaSourceRule, validateSchemaSource},
 	{validateProjectTuplesRule, validateProjectTuples},
 	{validateIndexCreationRule, validateIndexCreation},
+	{validateCaseResultTypesRule, validateCaseResultTypes},
```
Comment (kuba--) [inline sql/analyzer/validation_rules.go]: Just open question - doesn't make sense as a optimization to squash some rules?
For instance instead of 3 times looping, we may have one loop with some cases - loud thinking.

Comment (ajnavarro) [reply sql/analyzer/validation_rules.go]: this query phase is really fast compared with the rest. The idea of having separated rules is the synergy that we can obtain executing them again and again, interacting with other rules.

**Comment by ajnavarro** [comment]
@erizocosmico could you rebase please?
