### PR TITLE
sql: fix how nulls are sent to clients

### LINKED ISSUE #779: NULL is not printed in the resulting table
Hi,

When I used mysql client to connect the SQL server, I got the following table in which there were some empty fields that were supposed to be printed as `NULL`.

What I got: 
```bash
$ mysql -h 127.0.0.1 -u root
mysql> select * from tbl where timestamp = 3;
+--------------+-----------+-----------+-------------+
| id           | timestamp | col1      | col2       |
+--------------+-----------+-----------+-------------+
| id1          |         3 |           |           3 |
| id2          |         3 |           |           3 |
| id3          |         3 |         3 |             |
+--------------+-----------+-----------+-------------+
3 rows in set (0.51 sec)
```

What I expect: 
```bash
$ mysql -h 127.0.0.1 -u root
mysql> select * from tbl where timestamp = 3;
+--------------+-----------+-----------+-------------+
| id           | timestamp | col1      | col2        |
+--------------+-----------+-----------+-------------+
| id1          |         3 |   NULL    |           3 |
| id2          |         3 |    NULL   |           3 |
| id3          |         3 |         3 |    NULL     |
+--------------+-----------+-----------+-------------+
3 rows in set (0.51 sec)
```

It seems to me that in https://github.com/src-d/go-mysql-server/pull/753/files#diff-654bac6a55597b15c4a5d404095b4e69R306, shouldn't we handle both `nil` and `nullT`? For example:

```go
if _, ok := v.(nullT); ok || v == nil {
  return sqltypes.NULL, nil
}
```

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #779 

Fixing this, connecting from MySQL client broke. After much debugging, turns out it was because `@@version` and `@@version_comment` didn't exist (and thus, they were null), but the client was expecting something there. I just added both, but left them empty and the problem goes away.

### CODE REVIEW

File: sql/session.go [hunk 1]
```diff
@@ -175,6 +175,8 @@ func DefaultSessionConfig() map[string]TypedValue {
 		"ndbinfo_version":          TypedValue{Text, ""},
 		"sql_select_limit":         TypedValue{Int32, math.MaxInt32},
 		"transaction_isolation":    TypedValue{Text, "READ UNCOMMITTED"},
+		"version":                  TypedValue{Text, ""},
```
Comment (ajnavarro) [inline sql/session.go]: Maybe we can add the real version here to maintain consistency.

Comment (erizocosmico) [reply sql/session.go]: What version should we put? A fake mysql version? It might not be consistent with `VERSION()` though

Comment (ajnavarro) [reply sql/session.go]: we cannot use the same param as VERSION() is using here?

Comment (erizocosmico) [reply sql/session.go]: That's the thing, VERSION() doesn't even exist in plain go-mysql-server. It's registered in gitbase with a specific version.

Comment (ajnavarro) [reply sql/session.go]: oh, right, I mix both. Sorry for the noise.
