### PR TITLE
sql/plan: allow synchronous index creations

### LINKED ISSUE #271: Sync create index queries
There are some cases, such as tests or gitbase regression tests where you don't want to create the indexes in the background because you need them to be created before you start doing queries.

Do this manually requires a lot of knowledge about the insides and they are susceptible to change. By optionally letting the user decide if they should be sync or async we can abstract all this away and just use a query to create them.

It could be some config or environment variable.

WDYT? @ajnavarro

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #271

### CODE REVIEW

File: sql/plan/create_index.go [hunk 1]
```diff
@@ -43,12 +44,16 @@ func NewCreateIndex(
 	driver string,
 	config map[string]string,
 ) *CreateIndex {
+	async := config["async"] != "false"
+	// Remove async from the config, since it's not meant for the driver.
+	delete(config, "async")
```
Comment (ajnavarro) [inline sql/plan/create_index.go]: It doesn't do any bad keeping the property there.

File: sql/plan/create_index.go [hunk 2]
```diff
@@ -124,22 +129,32 @@ func (c *CreateIndex) RowIter(ctx *sql.Context) (sql.RowIter, error) {
...
+
+	log.WithField("async", c.Async).Info("starting to save the index")
 
-	log.Info("starting to save the index")
+	if c.Async {
+		go createIndex()
+	} else {
+		createIndex()
+		// wait for the index status to be updated
+		time.Sleep(50 * time.Millisecond)
```
Comment (ajnavarro) [inline sql/plan/create_index.go]: We should find a better solution for this.

**Comment by erizocosmico** [comment]
Fixed

File: sql/plan/create_index.go [hunk 3]
```diff
@@ -49,6 +50,7 @@ func NewCreateIndex(
 		Exprs:  exprs,
 		Driver: driver,
 		Config: config,
+		Async:  config["async"] != "false",
```
Comment (mcarmonaa) [inline sql/plan/create_index.go]: Is it ok using the configuration keys directly as strings instead of parameterize them through constants?

File: sql/index.go [hunk 4]
```diff
@@ -479,15 +482,17 @@ func (r *IndexRegistry) AddIndex(idx Index) (chan<- struct{}, error) {
 	r.indexOrder = append(r.indexOrder, key)
 	r.mut.Unlock()
 
-	var created = make(chan struct{})
+	var _created = make(chan struct{})
```
Comment (mcarmonaa) [inline sql/index.go]: Just curious about the underscore prefix, Is it frequently used or kind of standard in the community?

Comment (erizocosmico) [reply sql/index.go]: Nope, `created` and `ready` were used as named return arguments in the signature for documentation purposes, but they are restricted to one direction, so I can't really use them inside

File: sql/plan/create_index.go (hunk 3 above)
Comment (erizocosmico) [reply sql/plan/create_index.go]: I don't think async is gonna be called anything else anytime soon, and it's not used anywhere else, so no need to add two more constants for this

**Comment by erizocosmico** [comment]
Shall we merge this?
