### PR TITLE
Also check sockets bind to tcp6 and fail on all closed sockets

### LINKED ISSUE #821: Failing test for connection handler in Linux
`handler_linux_test.go` fails with the following error:

```
12:16 $ go test ./...
ok      github.com/src-d/go-mysql-server        2.559s
ok      github.com/src-d/go-mysql-server/auth   (cached)
ok      github.com/src-d/go-mysql-server/benchmark      (cached) [no tests to run]
ok      github.com/src-d/go-mysql-server/internal/regex (cached)
ok      github.com/src-d/go-mysql-server/internal/similartext   (cached)
?       github.com/src-d/go-mysql-server/internal/sockstate     [no test files]
ok      github.com/src-d/go-mysql-server/memory (cached)
time="2019-09-16T12:16:20+02:00" level=info msg="NewConnection: client 1"
--- FAIL: TestBrokenConnection (4.01s)
    require.go:172: 
                Error Trace:    handler_linux_test.go:51
                Error:          An error is expected but got nil.
                Test:           TestBrokenConnection
time="2019-09-16T12:16:24+02:00" level=info msg="NewConnection: client 1"
time="2019-09-16T12:16:24+02:00" level=info msg="NewConnection: client 1"
time="2019-09-16T12:16:24+02:00" level=info msg="NewConnection: client 2"
time="2019-09-16T12:16:24+02:00" level=info msg="kill query: pid 2"
time="2019-09-16T12:16:24+02:00" level=info msg="kill connection: id 1"
time="2019-09-16T12:16:24+02:00" level=info msg="NewConnection: client 1"
time="2019-09-16T12:16:24+02:00" level=info msg="NewConnection: client 2"
time="2019-09-16T12:16:27+02:00" level=info msg="NewConnection: client 2"
FAIL
FAIL    github.com/src-d/go-mysql-server/server 11.604s
ok      github.com/src-d/go-mysql-server/sql    (cached)
ok      github.com/src-d/go-mysql-server/sql/analyzer   (cached)
ok      github.com/src-d/go-mysql-server/sql/expression (cached)
ok      github.com/src-d/go-mysql-server/sql/expression/function        (cached)
ok      github.com/src-d/go-mysql-server/sql/expression/function/aggregation    (cached)
ok      github.com/src-d/go-mysql-server/sql/index      (cached)
ok      github.com/src-d/go-mysql-server/sql/index/pilosa       (cached)
ok      github.com/src-d/go-mysql-server/sql/parse      (cached)
ok      github.com/src-d/go-mysql-server/sql/plan       (cached)
?       github.com/src-d/go-mysql-server/test   [no test files]
FAIL
```

I am on current master (a478e1e07f52762154d8445e5c08422800340971), and I am running the tests from Arch Linux (kernel version 5.2.13-arch1-1-ARCH).

### PR DESCRIPTION
**Pull request by juanjux**
- Also parse `/proc/net/tcp6` because go will bind to it (too) on `Listen()`  if TCP v6 is enabled on the system, and then the socket will only show on `/proc/net/tcp6`. This fixes #821.

- Fail on all kinds of closed sockets, even if they were closed correctly, before the query completion, thus ensuring that the query is cancelled.

- Two explicit channel closings to ensure the goroutines exit ASAP.

### CODE REVIEW

File: internal/sockstate/netstat_darwin.go [hunk 1]
```diff
@@ -12,8 +12,8 @@ import (
 // elements that satisfy the accept function
 func tcpSocks(accept AcceptFn) ([]sockTabEntry, error) {
 	// (juanjux) TODO: not implemented
-	logrus.Info("Connection checking not implemented for Darwin")
-	return []sockTabEntry{}, nil
+	logrus.Info("Connection checking not implemented for Windows")
```
Comment (agarciamontoro) [inline internal/sockstate/netstat_darwin.go]: Shouldn't this be still Darwin?

Comment (erizocosmico) [inline internal/sockstate/netstat_darwin.go]: Warn instead of info maybe?

File: internal/sockstate/netstat_linux.go [hunk 2]
```diff
@@ -120,6 +122,23 @@ func parseIPv4(s string) (net.IP, error) {
 	return ip, nil
 }
 
+func parseIPv6(s string) (net.IP, error) {
```
Comment (erizocosmico) [inline internal/sockstate/netstat_linux.go]: There's a `net.ParseIP` function already https://golang.org/pkg/net/#ParseIP, which parses both IPv4 and IPv6

Comment (juanjux) [reply internal/sockstate/netstat_linux.go]: It's not an IP in the usual form the the format used by `/proc/net/tcp` like `0201A8C0:88F0`.

File: internal/sockstate/netstat_darwin.go (hunk 1 above)
Comment (juanjux) [reply internal/sockstate/netstat_darwin.go]: Agreed, fixed.

Comment (juanjux) [reply internal/sockstate/netstat_darwin.go]: ups, thanks, fixed.

**Comment by erizocosmico** [comment]
@juanjux remember to sign de DCO

**Comment by juanjux** [comment]
@erizocosmico yep, that's what happen when you commit code from VMs or other people machines without all your git/gpg config scaffolding :/

**Comment by TheWinds** [comment]
On linux system,if TCP v6 is  disabled on the system, open /proc/net/tcp6 will produce the error `/proc/net/tcp6: No such file or directory`.
How to slove this bug？
```go
func tcpSocks(accept AcceptFn) ([]sockTabEntry, error) {
	paths := [2]string{pathTCP4Tab, pathTCP6Tab}
	var allTabs []sockTabEntry
	for _, p := range paths {
		f, err := os.Open(p)
		defer func() {
			_ = f.Close()
		}()
		if err != nil {
			return nil, err
		}

		t, err := parseSocktab(f, accept)
		if err != nil {
			return nil, err
		}
		allTabs = append(allTabs, t...)

	}
	extractProcInfo(allTabs)
	return allTabs, nil
}
```

**Comment by erizocosmico** [comment]
@TheWinds this project is no longer maintained, you can report this on it's new home: https://github.com/dolthub/go-mysql-server
